### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 922.00 MiB...........

### ISSUE THREAD

**Issue by ZY0723** [wangliang88/cvpr_ct_synthesis#5]
Traceback (most recent call last):
  File "main.py", line 244, in <module>
    train(args)
  File "main.py", line 107, in train
    interpolation_out,sr_out_left,sr_out_right,interpolation_out_2_4,sr_out_2_4_left,sr_out_2_4_right,m_items,interpolation_out_05,sr_out_05_left,sr_out_05_right,softmax_score_query,softmax_score_memory,separateness_loss,compactness_loss= model(input_volume.float().cuda(0),m_items,train=True)
  File "/root/miniconda3/envs/ctsyn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/ct_synthesis-master/model/new_model_x2.py", line 67, in forward
    sr_out_05_left_right = self.model1(sr_out_2_4_left_right)[:,:,:,:-1]#1,1.5,2,2.5,3,3.5.....13,|13.5
  File "/root/miniconda3/envs/ctsyn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/ct_synthesis-master/basicmodel/basic_x2/han.py", line 197, in forward
    x = self.head(x1)
  File "/root/miniconda3/envs/ctsyn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ctsyn/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/root/miniconda3/envs/ctsyn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ctsyn/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/envs/ctsyn/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 922.00 MiB (GPU 0; 10.76 GiB total capacity; 8.53 GiB already allocated; 55.56 MiB free; 9.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**i have another question. When I modify the code, it always shows that the video memory is not enough. What size of the existing memory did you use? I have tried 2080Ti and 3090. The maximum video memory is 36GB, but it is still not enough.Thanks**

**Comment by VLAD-KONATA** [comment]
have you solved the problem? i met this too

**Comment by ZY0723** [comment]
no，I think it has some problems, I don’t use it anymore.

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/22/2025 23:41 |
| To | lwang88/ct_synthesis ***@***.***> |
| Cc | ZY0723 ***@***.***>,
State ***@***.***> |
| Subject | Re: [lwang88/ct_synthesis] RuntimeError: CUDA out of memory. Tried to allocate 922.00 MiB........... (Issue #5) |

have you solved the problem? i met this too

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

VLAD-KONATA left a comment (lwang88/ct_synthesis#5)

have you solved the problem? i met this too

**Comment by VLAD-KONATA** [comment]
> no，I think it has some problems, I don’t use it anymore.
> […](#)

thx，i think maybe the network is too complex so exhaust the whole memory

**Comment by ZY0723** [comment]
i think the code has some problems.  i checked the middle process in code， not just about GPU‘s memory. gold bless you.

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/23/2025 00:44 |
| To | lwang88/ct_synthesis ***@***.***> |
| Cc | ZY0723 ***@***.***>,
State ***@***.***> |
| Subject | Re: [lwang88/ct_synthesis] RuntimeError: CUDA out of memory. Tried to allocate 922.00 MiB........... (Issue #5) |

no，I think it has some problems, I don’t use it anymore.
…

thx，i think maybe the network is too complex so exhaust the whole memory

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

VLAD-KONATA left a comment (lwang88/ct_synthesis#5)

no，I think it has some problems, I don’t use it anymore.
…

thx，i think maybe the network is too complex so exhaust the whole memory
